# Generated by Django 4.0.3 on 2022-06-09 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=6, verbose_name='Номер дома')),
                ('city', models.CharField(max_length=100, verbose_name='Город/Населенный пункт')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('post_code', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Введен неверный номер телефона', regex='(?:(?:8|\\+7)[\\- ]?)?(?:\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}')], verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
