# Generated by Django 4.0.3 on 2022-05-08 13:21

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=products.models.upload_gallery_image, verbose_name='Картинка'),
        ),
    ]
