# Generated by Django 4.0.3 on 2022-05-10 09:07

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[products.models.validate_range], verbose_name='Скидка, %'),
        ),
    ]
